destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    auth:
      type: basic
      username: "${GRAFANA_CLOUD_USERNAME_METRICS}"
      password: "${GRAFANA_CLOUD_PASSWORD_METRICS}"
  - name: grafana-cloud-logs
    type: loki
    auth:
      type: basic
      username: "${GRAFANA_CLOUD_USERNAME_LOGS}"
      password: "${GRAFANA_CLOUD_PASSWORD_LOGS}"
  - name: grafana-cloud-otlp-endpoint
    type: otlp
    protocol: http
    auth:
      type: basic
      username: "${GRAFANA_CLOUD_USERNAME_OTLP}"
      password: "${GRAFANA_CLOUD_PASSWORD_OTLP}"
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true
clusterMetrics:
  enabled: true
  kube-state-metrics:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"

alloy-metrics:
  enabled: true
  controller:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"