apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:v0.15.0
        env:
        - name: DATA_SOURCE_URI
          valueFrom:
            secretKeyRef:
              name: postgres-exporter-secrets
              key: DATA_SOURCE_URI
        - name: DATA_SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-exporter-secrets
              key: DATA_SOURCE_USER
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-exporter-secrets
              key: DATA_SOURCE_PASS
        ports:
        - containerPort: 9187
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
