name: CI CD Thinkshare Backend

on:
  push:
    branches: [ terraform, main ]
  pull_request:
    branches: [ main,terraform]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: cd backend && go mod download
      - name: Lint
        run: cd backend && go install golang.org/x/lint/golint@latest && golint ./...

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: cd backend && go mod download
      - name: Run unit tests
        run: cd backend && go test -v ./tests/unit/...

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-test
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: test
      PGPASSWORD: test
      PGDATABASE: testdb
      PGSSLMODE: disable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: cd backend && go mod download
      - name: Debug env
        run: env | grep PG
      - name: Run integration tests
        run: cd backend && go test -v ./tests/integration/...

  docker-build-backend:
    name: Build Docker image (Backend)
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t thinkshare-backend:latest ./backend
      - name: Tag Docker image as v1
        run: docker tag thinkshare-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/thinkshare-backend:latest
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image v1
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/thinkshare-backend:latest

  docker-build-frontend:
    name: Build Docker image (Frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t thinkshare-frontend:latest ./frontend
      # Décommenter pour push sur Docker Hub
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}.DOCKERHUB_TOKEN }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Push Docker image      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/thinkshare-frontend:latest


      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/thinkshare-frontend:latest

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
      - name: Install dependencies
        run: |
          cd frontend
          flutter pub get
      - name: Run frontend tests
        run: |
          cd frontend
          flutter test

  terraform-deploy:
    name: Deploy on Azure with Terraform
    runs-on: ubuntu-latest
    needs: docker-build-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: cd backend/infra/terraform && terraform init

      - name: Terraform Apply
        run: cd backend/infra/terraform && terraform apply -auto-approve